#!/usr/bin/env python3
"""
Generate GitHub Actions workflow files from user_config.yaml schedules.

Usage:
    python scripts/gen_workflows.py
    git add .github/workflows/
    git commit -m "update schedules"
    git push
"""
from __future__ import annotations

import io
import os
import sys
from pathlib import Path

# Force UTF-8 stdout so emoji in YAML labels don't crash on Windows consoles
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
else:
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

# Allow running from repo root or scripts/
ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

import yaml

# Beijing → UTC cron mapping (supports common hours; extend as needed)
BEIJING_TO_UTC_CRON: dict[str, str] = {
    "00:00": "0 16 * * *",
    "01:00": "0 17 * * *",
    "02:00": "0 18 * * *",
    "03:00": "0 19 * * *",
    "04:00": "0 20 * * *",
    "05:00": "0 21 * * *",
    "06:00": "0 22 * * *",
    "07:00": "0 23 * * *",
    "08:00": "0 0 * * *",
    "09:00": "0 1 * * *",
    "10:00": "0 2 * * *",
    "11:00": "0 3 * * *",
    "12:00": "0 4 * * *",
    "13:00": "0 5 * * *",
    "14:00": "0 6 * * *",
    "15:00": "0 7 * * *",
    "16:00": "0 8 * * *",
    "17:00": "0 9 * * *",
    "18:00": "0 10 * * *",
    "19:00": "0 11 * * *",
    "20:00": "0 12 * * *",
    "21:00": "0 13 * * *",
    "22:00": "0 14 * * *",
    "23:00": "0 15 * * *",
}

WORKFLOW_TEMPLATE = """\
# Auto-generated by scripts/gen_workflows.py — do not edit manually
name: "{label} ({time})"

on:
  schedule:
    - cron: '{cron}'
  workflow_dispatch:
    inputs:
      schedule_index:
        description: '时间段索引'
        default: '{index}'
        required: false

jobs:
  digest:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run digest
        env:
          OPENAI_API_KEY: ${{{{ secrets.OPENAI_API_KEY }}}}
          DEEPSEEK_API_KEY: ${{{{ secrets.DEEPSEEK_API_KEY }}}}
          ANTHROPIC_API_KEY: ${{{{ secrets.ANTHROPIC_API_KEY }}}}
          SERVERCHAN_KEY: ${{{{ secrets.SERVERCHAN_KEY }}}}
        run: python main.py --schedule-index {index}

      - name: Commit updated data
        run: |
          git config user.name "digest-bot"
          git config user.email "bot@digest.local"
          git add data/seen_urls.json archive/
          git diff --staged --quiet || git commit -m "{label} $(date +%Y-%m-%d)"
          git push
"""


def load_user_config() -> dict:
    cfg_path = ROOT / "config" / "user_config.yaml"
    with open(cfg_path, encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def sanitize_filename(time_str: str) -> str:
    return time_str.replace(":", "")


def main() -> None:
    cfg = load_user_config()
    schedules = cfg.get("schedule", [])
    workflows_dir = ROOT / ".github" / "workflows"
    workflows_dir.mkdir(parents=True, exist_ok=True)

    # Remove old auto-generated workflow files
    for old in workflows_dir.glob("push_*.yml"):
        old.unlink()
        print(f"  [DEL] Removed old workflow: {old.name}")

    generated = 0
    for idx, sched in enumerate(schedules):
        if not sched.get("enabled", True):
            print(f"  [SKIP] Disabled schedule [{idx}]: {sched.get('label', '')}")
            continue

        time_str: str = sched.get("time", "09:00")
        label: str = sched.get("label", f"AI Digest {time_str}")
        # Strip emoji for safe filename/cron lookup
        time_key = time_str.strip()

        cron = BEIJING_TO_UTC_CRON.get(time_key)
        if cron is None:
            print(
                f"  [WARN] No UTC mapping for time {time_key!r}. "
                "Please add it to BEIJING_TO_UTC_CRON in gen_workflows.py."
            )
            continue

        filename = f"push_{sanitize_filename(time_str)}.yml"
        content = WORKFLOW_TEMPLATE.format(
            label=label,
            time=time_str,
            cron=cron,
            index=idx,
        )

        out_path = workflows_dir / filename
        out_path.write_text(content, encoding="utf-8")
        print(f"  [OK] Generated: .github/workflows/{filename}  (cron: {cron}  UTC)")
        generated += 1

    print(f"\nDone -- {generated} workflow(s) generated.")
    print("Next steps:")
    print("  git add .github/workflows/")
    print('  git commit -m "update schedules"')
    print("  git push")


if __name__ == "__main__":
    main()
